### PR TITLE
Fix removing capital S from toot

### PR DESCRIPTION
**Pull request by f0086**
All letter S' where removed from the toot.

### CODE REVIEW

**Review by KEINOS — APPROVED** [review]
https://user-images.githubusercontent.com/11840938/127578500-3235cc48-d23f-4cd0-92e6-bacba9fabb8e.mp4

**Comment by KEINOS** [comment]
@f0086 

Wow!! Let's merge it!

Thank you for picking my repo up!

**Comment by f0086** [comment]
Thanks for the lightning fast response and merge! :heart: 
Can you push a new image build to docker hub as well?

**Comment by KEINOS** [comment]
@f0086 
I pushed the latest image [`848132513fdb`](https://hub.docker.com/layers/keinos/mastodon-tooter/latest/images/sha256-848132513fdb3d6c47896776e9f0d8c681eed70b4177d620aad666d86fe2abb1?context=explore) ! Plz check.

p.s.
I thought I set to build automatically on a new git push to the repo, but I didn't realize that the Docker HUB's automated build became only for the Pro version. 😭 

Anyways thanks for the PR!!!

**Pull request merged**
